name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Build Image
      run: sudo docker build -t cloudflare-ddns .
    - name: Docker Hub Login
      run: echo $DOCKER_SECRETS | docker login --username=peterlee0127  --password-stdin 
    


    #- name: Push to GitHub Packages
    #  uses: docker/build-push-action@v1
    #  with:
    #   username: ${{ github.actor }}
    #    password: ${{ secrets.GITHUB_TOKEN }}
    #    registry: docker.pkg.github.com
    #    repository: peterlee0127/cloudflare-ddns/cloudflare-ddns
    #    tag_with_ref: true

