name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Build Image
      run: sudo docker build -t cloudflare-ddns .
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRETS }}
    - name: Tag Docker Image
      run: docker tag cloudflare-ddns ${{ secrets.DOCKER_USERNAME }}/cloudflare-ddns
    - name: Push Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cloudflare-ddns
    - name: Login to GitHub Packages
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
    - name: Tag to Github Packages
      run: docker tag cloudflare-ddns ghcr.io/${{ github.actor }}/cloudflare-ddns
    - name: Push to Github Packages
      run: docker push ghcr.io/${{ github.actor }}/cloudflare-ddns 
